baseURL = "https://codebrewcyber.github.io/"
defaultContentLanguage = "en"
enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 20

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[caches]
  [caches.images]
    dir = ":cacheDir/images"

